%YAML:1.0
---
format: 3
thresholdStep: 1.
minThreshold: 127.
maxThreshold: 128.
minRepeatability: 0
minDistBetweenBlobs: 10.
filterByColor: 1
blobColor: 255
filterByArea: 1
minArea: 750.
maxArea: 15000000000.
filterByCircularity: 0
minCircularity: 0.0
maxCircularity: 1.
filterByInertia: 0
minInertiaRatio: 0.0
maxInertiaRatio: 1.
filterByConvexity: 0
minConvexity: 0.0
maxConvexity: 1.

# See https://www.learnopencv.com/blob-detection-using-opencv-python-c/
# for an explanation on modifying these parameters.
# Unlike the tutorial, these parameters are being saved to a (yaml) file,
# so the syntax is different but the concepts are still the same.
